"""users jwt

Revision ID: 750c86fc2d17
Revises: d3a97f452d07
Create Date: 2022-01-12 18:25:38.461353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750c86fc2d17'
down_revision = 'd3a97f452d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token')
        batch_op.drop_column('token_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
